### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by RichardScottOZ** [parsee-ai/parsee-pdf-reader#5]
This is really interesting, thanks!

I was wondering how you approached things in practice:

Find pdf
It automatically OCRs
Then process pdfs etc.

I was wondering if you had a general approach built for timeouts etc. when things were taking a long time and things along those lines.

**Comment by thf24** [comment]
Hi,

the OCR is automatically triggered when no elements are found with the "normal" retrieval method, so if the PDF is not text-based for example or if the file is an image.

Timeouts are usually not a problem, there is only a case for 90 degree rotated pages and large tables on them where I believe PDFminer will take quite some time to process it. In general the focus so far is not on optimal performance but rather to achieve some high quality output. We'll be focusing on performance improvments later on.
